# Generated by Django 5.2.17 on 2026-08-19 11:56

import django.core.validators
import event_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=event_management.validators._SafeUploadTo('expense_receipts'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Unsupported file type. Allowed: pdf, doc, docx, jpg, jpeg, png.'), event_management.validators.validate_document_size]),
        ),
    ]
