# Generated by Django 5.2.17 on 2026-08-19 11:56

import django.core.validators
import event_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_maintenanceschedule_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event_management.validators._SafeUploadTo('venue_images'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message='Unsupported image type. Allowed: jpg, jpeg, png, gif, webp.'), event_management.validators.validate_image_size, event_management.validators.validate_image_contents]),
        ),
    ]
