# Generated by Django 5.2.17 on 2026-08-14 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='1-based queue position among currently active (waiting/notified) entries for this event.')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('notified', 'Notified — pending registration'), ('expired', 'Invitation Expired'), ('promoted', 'Promoted — registered'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'joined_at'],
                'indexes': [models.Index(fields=['event', 'status', 'position'], name='events_wait_event_i_e3a17c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'notified'])), fields=('event', 'user'), name='unique_active_waitlist_entry_per_event_user')],
            },
        ),
    ]
