# Generated by Django 5.2.17 on 2026-08-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_waitlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
