# Generated by Django 5.2.17 on 2026-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='site_name',
            field=models.CharField(default='Eventra', max_length=100),
        ),
    ]
