# Generated by Django 5.2.17 on 2026-08-19 11:56

import django.core.validators
import event_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendorcontract_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=event_management.validators._SafeUploadTo('vendor_contracts'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Unsupported file type. Allowed: pdf, doc, docx, jpg, jpeg, png.'), event_management.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='vendordocument',
            name='file',
            field=models.FileField(upload_to=event_management.validators._SafeUploadTo('vendor_documents'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Unsupported file type. Allowed: pdf, doc, docx, jpg, jpeg, png.'), event_management.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=event_management.validators._SafeUploadTo('vendor_logos'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message='Unsupported image type. Allowed: jpg, jpeg, png, gif, webp.'), event_management.validators.validate_image_size, event_management.validators.validate_image_contents]),
        ),
    ]
