# Generated by Django 5.2.17 on 2026-08-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_registration_status'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalstep',
            new_name='workflow_ap_content_23ead7_idx',
            old_name='workflow_ap_content_c6f2f7_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='workflow_no_user_id_7a7502_idx',
            old_name='workflow_no_user_id_5f2b8e_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_event',
            field=models.ForeignKey(blank=True, help_text='The event this notification is about, where applicable — lets the UI group/filter by event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='events.event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval', 'Approval'), ('reminder', 'Reminder'), ('staff', 'Staff'), ('vendor', 'Vendor'), ('payment', 'Payment'), ('announcement', 'Announcement'), ('system', 'System'), ('registration', 'Registration'), ('ticket', 'Ticket'), ('certificate', 'Certificate'), ('checkin', 'Check-in'), ('capacity', 'Capacity Warning'), ('budget', 'Budget Warning'), ('task', 'Task Deadline')], default='system', max_length=20),
        ),
    ]
