# Generated by Django 5.2.17 on 2026-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_rename_workflow_ap_content_c6f2f7_idx_workflow_ap_content_23ead7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval', 'Approval'), ('reminder', 'Reminder'), ('staff', 'Staff'), ('vendor', 'Vendor'), ('payment', 'Payment'), ('announcement', 'Announcement'), ('system', 'System'), ('registration', 'Registration'), ('ticket', 'Ticket'), ('certificate', 'Certificate'), ('checkin', 'Check-in'), ('capacity', 'Capacity Warning'), ('budget', 'Budget Warning'), ('task', 'Task Deadline'), ('event_cancelled', 'Event Cancelled'), ('event_rescheduled', 'Event Rescheduled')], default='system', max_length=20),
        ),
    ]
